"""Symbols vulture cannot see used: the Colab notebook's entry points and test-only oracles."""

from morphological import signature_vectorize
from semantic import large_models
from syntactic import function_ngram, typ_ngram
from syntactic import signature_vectorize as syntactic_signature

#: Called from scripts/compute_large_embeddings.ipynb, which vulture does not scan.
large_models.models_for_choice
large_models.ensure_corpus_data
large_models.gpu_memory_summary

#: Dense references the sparse path is asserted against; production uses the sparse builders.
signature_vectorize.morph_signature_1_2_3gram_vectors
signature_vectorize.morph_signature_1_2_3gram_psalm_vectors
signature_vectorize.morph_signature_1_2_3gram_vectors
typ_ngram.phrase_typ_1_2_3gram_vectors
typ_ngram.phrase_typ_1_2_3gram_psalm_vectors
function_ngram.phrase_function_1_2_3gram_vectors
function_ngram.phrase_function_1_2_3gram_psalm_vectors
syntactic_signature.phrase_signature_1_2_3gram_vectors
syntactic_signature.phrase_signature_1_2_3gram_psalm_vectors
